export enum ExceptionCode {
  // Authentication & Authorization
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_EMAIL_TAKEN = 'USER_EMAIL_TAKEN',

  // Organization
  ORG_NOT_FOUND = 'ORG_NOT_FOUND',
  ORG_SLUG_TAKEN = 'ORG_SLUG_TAKEN',
  ORG_MEMBER_ALREADY_EXISTS = 'ORG_MEMBER_ALREADY_EXISTS',
  ORG_MEMBER_NOT_FOUND = 'ORG_MEMBER_NOT_FOUND',
  ORG_CANNOT_REMOVE_OWNER = 'ORG_CANNOT_REMOVE_OWNER',
  ORG_INVITATION_EXPIRED = 'ORG_INVITATION_EXPIRED',
  ORG_INVITATION_NOT_FOUND = 'ORG_INVITATION_NOT_FOUND',

  // Project
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_KEY_TAKEN = 'PROJECT_KEY_TAKEN',
  PROJECT_MEMBER_ALREADY_EXISTS = 'PROJECT_MEMBER_ALREADY_EXISTS',
  PROJECT_MEMBER_NOT_FOUND = 'PROJECT_MEMBER_NOT_FOUND',

  // Issue
  ISSUE_NOT_FOUND = 'ISSUE_NOT_FOUND',
  ISSUE_INVALID_TRANSITION = 'ISSUE_INVALID_TRANSITION',
  ISSUE_CIRCULAR_DEPENDENCY = 'ISSUE_CIRCULAR_DEPENDENCY',
  ISSUE_PARENT_SAME_AS_CHILD = 'ISSUE_PARENT_SAME_AS_CHILD',

  // Sprint
  SPRINT_NOT_FOUND = 'SPRINT_NOT_FOUND',
  SPRINT_ALREADY_ACTIVE = 'SPRINT_ALREADY_ACTIVE',
  SPRINT_ALREADY_COMPLETED = 'SPRINT_ALREADY_COMPLETED',

  // Workflow
  WORKFLOW_NOT_FOUND = 'WORKFLOW_NOT_FOUND',
  WORKFLOW_INVALID_TRANSITION = 'WORKFLOW_INVALID_TRANSITION',

  // Version
  VERSION_NOT_FOUND = 'VERSION_NOT_FOUND',
  VERSION_ALREADY_RELEASED = 'VERSION_ALREADY_RELEASED',

  // Attachment
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',
  ATTACHMENT_UPLOAD_FAILED = 'ATTACHMENT_UPLOAD_FAILED',
  ATTACHMENT_SIZE_EXCEEDED = 'ATTACHMENT_SIZE_EXCEEDED',

  // General
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  OPERATION_NOT_ALLOWED = 'OPERATION_NOT_ALLOWED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
}
